# Generated by Django 5.1.1 on 2024-10-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_cartitem_cart_remove_cartitem_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='event_type',
            field=models.CharField(default='Others', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
