# Generated by Django 5.1.1 on 2024-10-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='taken_by_provider',
            field=models.BooleanField(default=False),
        ),
    ]
