# Generated by Django 5.1.1 on 2024-11-03 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_mpesa_code_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
